# A thing that has almost everything in it.

version: 2

registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/octocat
    username: octocat
    password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
    
updates:
  - package-ecosystem: "pip"
    directory: "/project/requirements.txt"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "bundler" 
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "something"
      - dependency-name: "something else"
        dependency-type: "production"
    assignees:
      - "mona"
    commit-message:
      prefix: "bundler-magic"
    insecure-external-code-execution: allow
    ignore:
      - dependency-name: "express"
        versions: ["4.x", "5.x"]
      - dependency-name: "lodash"
      - dependency-name: "aws-sdk"
        update-types: ["version-update:semver-patch"]
    labels:
      - "npm"
      - "dependencies"
    milestone: 4
    open-pull-requests-limit: 10
    pull-request-branch-name:
      seperator: "-"
    rebase-strategy: "disabled"
    registries:
      - maven-github
    
